import { HP, type Regla } from "./tipos";

/**
 * 07 · WEB, LANDINGS Y CRO
 *
 * Las reglas cuelgan de un paso del embudo: ¿llega? ¿entiende? ¿confía? ¿puede?
 *
 * Disciplina que no se rompe: **no se inventan porcentajes de mejora**. Es facilísimo
 * escribir «bajando el LCP subiríais la conversión un 15 %» y en cuanto alguien lo
 * pregunte se cae el informe entero. Lo que sí se dice: el dato medido y el umbral con su
 * fuente.
 */
export const REGLAS: Regla[] = [
  // ======================= 1 · ¿LLEGA? =======================
  {
    id: "lcp_malo", funcion: 7, necesita: ["campo.lcp_movil"],
    evaluar: (v) => v.num("campo.lcp_movil") > 4000 ? HP("llega",
      "La web tarda demasiado en móvil, con usuarios reales",
      `El percentil 75 de LCP en móvil es de ${(v.num("campo.lcp_movil") / 1000).toFixed(1)} s, medido sobre visitantes reales de los últimos 28 días.`,
      "Google considera bueno por debajo de 2,5 s y malo por encima de 4. Una parte de quien entra desde un anuncio se va antes de ver nada, y esa parte se ha pagado igual.",
      "Atacar primero la imagen de la primera pantalla y los scripts que bloquean el render. Es donde está casi siempre y es lo más barato de arreglar.",
      "p1") : null,
  },
  {
    id: "lcp_mejorable", funcion: 7, necesita: ["campo.lcp_movil"],
    evaluar: (v) => {
      const t = v.num("campo.lcp_movil");
      return t > 2500 && t <= 4000 ? HP("llega",
        "La velocidad en móvil está en la franja intermedia",
        `El percentil 75 de LCP en móvil es de ${(t / 1000).toFixed(1)} s.`,
        "No es un problema urgente, pero está por encima de los 2,5 s que Google considera buenos, y eso pesa tanto en la experiencia como en el posicionamiento.",
        "Con optimizar las imágenes suele bastar para bajar del umbral.",
        "p2") : null;
    },
  },
  {
    id: "lcp_bueno", funcion: 7, necesita: ["campo.lcp_movil"],
    evaluar: (v) => v.num("campo.lcp_movil") <= 2500 ? HP("llega",
      "La web carga rápido en móvil",
      `El percentil 75 de LCP en móvil es de ${(v.num("campo.lcp_movil") / 1000).toFixed(1)} s, dentro de lo que Google considera bueno.`,
      "La velocidad no es un problema aquí. Lo que se invierta en captación no se pierde en la carga.",
      "Mantenerlo: vigilarlo cada vez que se añada una herramienta nueva, que es cuando se estropea.",
      "p3", "alta", true) : null,
  },
  {
    id: "cls_malo", funcion: 7, necesita: ["campo.cls_movil"],
    evaluar: (v) => v.num("campo.cls_movil") > 0.25 ? HP("llega",
      "El contenido se mueve mientras carga",
      `El CLS real en móvil es de ${v.num("campo.cls_movil").toFixed(2)}; el umbral de Google para considerarlo bueno es 0,1.`,
      "La gente va a pulsar donde no quería. En un formulario o en un botón de contacto, eso es un abandono.",
      "Declarar width y height en las imágenes y reservar el hueco de lo que carga después, como banners y anuncios.",
      "p1") : null,
  },
  {
    id: "ttfb_malo", funcion: 7, necesita: ["campo.ttfb_movil"],
    evaluar: (v) => v.num("campo.ttfb_movil") > 1800 ? HP("llega",
      "El servidor tarda en contestar",
      `El TTFB real en móvil es de ${Math.round(v.num("campo.ttfb_movil"))} ms; por encima de 1.800 se considera malo.`,
      "Esto no se arregla optimizando la web: es alojamiento. Todo lo demás que se optimice parte con ese retraso ya encima.",
      "Revisar el plan de alojamiento y poner una CDN delante. Suele ser el cambio con mejor relación entre coste y resultado.",
      "p1") : null,
  },
  {
    id: "imagenes_pesadas", funcion: 7, necesita: ["web.img_peso", "web.img_formato_antiguo"],
    evaluar: (v) => v.num("web.img_peso") > 2000 ? HP("llega",
      "Las imágenes pesan demasiado",
      `La página descarga ${(v.num("web.img_peso") / 1024).toFixed(1)} MB en imágenes, y ${v.num("web.img_formato_antiguo")} están en JPEG o PNG en vez de formatos modernos.`,
      "Es lo que hace lenta la primera visita, sobre todo en móvil con datos. Y es la parte más fácil de arreglar de toda la web.",
      "Convertir a WebP o AVIF y servir cada imagen al tamaño en que se ve. No requiere tocar el diseño.",
      "p1") : null,
  },
  {
    id: "imagenes_sobredimensionadas", funcion: 7, necesita: ["web.img_sobredimensionadas"],
    evaluar: (v) => v.num("web.img_sobredimensionadas") >= 3 ? HP("llega",
      "Se sirven imágenes mucho más grandes de lo que se ven",
      `${v.num("web.img_sobredimensionadas")} imágenes se descargan al doble o más del tamaño en que se muestran.`,
      "Se paga el ancho de banda de una foto enorme para enseñar una pequeña. En móvil esto es lo que más tiempo cuesta y no aporta nada visible.",
      "Generar varias versiones y servir la que corresponda con srcset. La mayoría de gestores lo hacen solos si se activa.",
      "p2") : null,
  },
  {
    id: "imagen_hero_pesada", funcion: 7, necesita: ["web.img_hero_peso"],
    evaluar: (v) => v.num("web.img_hero_peso") > 500 ? HP("llega",
      "La imagen principal pesa demasiado",
      `La imagen más pesada de la primera pantalla ocupa ${v.num("web.img_hero_peso")} KB.`,
      "Es casi siempre el elemento que mide el LCP, así que es la causa directa del número de velocidad. Hasta que baje, el resto de optimizaciones se notan poco.",
      "Comprimirla, convertirla a WebP y cargarla con prioridad alta.",
      "p1") : null,
  },
  {
    id: "sin_dimensiones_imagen", funcion: 7, necesita: ["web.img_sin_dimensiones", "web.img_total"],
    evaluar: (v) => v.num("web.img_sin_dimensiones") > v.num("web.img_total") / 2 ? HP("llega",
      "Las imágenes no declaran su tamaño",
      `${v.num("web.img_sin_dimensiones")} de ${v.num("web.img_total")} imágenes no llevan width ni height.`,
      "El navegador no sabe cuánto hueco reservar, así que el contenido salta cuando cada imagen termina de cargar. Es la causa habitual de que la gente pulse donde no quería.",
      "Añadir width y height a cada imagen. Es un atributo, no un rediseño.",
      "p2") : null,
  },
  {
    id: "scroll_horizontal", funcion: 7, necesita: ["movil.scroll_horizontal"],
    evaluar: (v) => v.bool("movil.scroll_horizontal") ? HP("llega",
      "En móvil se puede desplazar la página hacia los lados",
      "El contenido es más ancho que la pantalla a 390 px.",
      "Es el fallo más delatador de una web que no se ha probado en móvil, y desplaza el texto fuera de la vista mientras se lee.",
      "Encontrar el elemento que se desborda, normalmente una imagen o una tabla sin ancho máximo, y limitarlo.",
      "p1") : null,
  },
  {
    id: "youtube_incrustado", funcion: 7, necesita: ["web.youtube"],
    evaluar: (v) => v.num("web.youtube") > 0 ? HP("llega",
      "Hay vídeo de YouTube incrustado de la forma pesada",
      `${v.num("web.youtube")} iframe${v.num("web.youtube") > 1 ? "s" : ""} de YouTube en la página.`,
      "Cada uno descarga cientos de kilobytes y pone cookies de Google aunque nadie le dé al play. Cuesta velocidad y complica el consentimiento.",
      "Sustituirlo por una miniatura que cargue el reproductor solo al pulsarlo. Hay soluciones hechas y se cambia en una hora.",
      "p2") : null,
  },

  // ======================= 2 · ¿ENTIENDE? =======================
  {
    id: "sin_cta_visible", funcion: 7, necesita: ["movil.cta_primera_pantalla"],
    evaluar: (v) => v.lista("movil.cta_primera_pantalla").length === 0 ? HP("entiende",
      "No hay ninguna acción visible sin hacer scroll",
      "En la primera pantalla de móvil no aparece ningún botón ni enlace de contacto.",
      "Quien llega desde un anuncio ya venía convencido: si no encuentra qué pulsar en los primeros dos segundos, se va.",
      "Poner una llamada a la acción por encima del pliegue, con el mismo mensaje que traía el anuncio.",
      "p1") : null,
  },
  {
    id: "demasiados_cta", funcion: 7, necesita: ["movil.cta_primera_pantalla"],
    evaluar: (v) => v.lista("movil.cta_primera_pantalla").length > 4 ? HP("entiende",
      "Demasiadas acciones compiten en la primera pantalla",
      `Se ven ${v.lista("movil.cta_primera_pantalla").length} enlaces o botones distintos sin hacer scroll.`,
      "Tres llamadas a la acción es ninguna: la atención se reparte y no se sigue ninguna.",
      "Dejar una acción principal clara y bajar el resto en jerarquía visual.",
      "p2") : null,
  },
  {
    id: "sin_sistema_visual", funcion: 7, necesita: ["estilo.colores_texto", "estilo.tamaños"],
    evaluar: (v) => v.num("estilo.colores_texto") > 12 || v.num("estilo.tamaños") > 12 ? HP("entiende",
      "No hay un sistema de diseño detrás",
      `La página usa ${v.num("estilo.colores_texto")} colores de texto distintos y ${v.num("estilo.tamaños")} tamaños de letra.`,
      "No es un problema estético: significa que cada parte la hizo alguien distinto sin una referencia común. Cualquier página nueva que se añada va a desentonar, y mantener coherencia cuesta el doble.",
      "Fijar una escala tipográfica y una paleta cerradas, y aplicarlas. Es la base de que todo lo que se produzca después salga coherente sin pensarlo.",
      "p2") : null,
  },
  {
    id: "sistema_visual_ok", funcion: 7, necesita: ["estilo.colores_texto", "estilo.tamaños"],
    evaluar: (v) => v.num("estilo.colores_texto") <= 6 && v.num("estilo.tamaños") <= 8 ? HP("entiende",
      "Hay criterio visual",
      `Solo ${v.num("estilo.colores_texto")} colores de texto y ${v.num("estilo.tamaños")} tamaños de letra en toda la página.`,
      "Hay un sistema detrás. Lo que se produzca nuevo va a encajar sin esfuerzo.",
      "Mantenerlo documentado para que no se degrade con el tiempo.",
      "p3", "alta", true) : null,
  },
  {
    id: "fuentes_google", funcion: 7, necesita: ["estilo.fuentes_google"],
    evaluar: (v) => v.num("estilo.fuentes_google") > 0 ? HP("entiende",
      "Las tipografías se sirven desde el CDN de Google",
      `Se descargan ${v.num("estilo.fuentes_google")} ficheros de tipografía desde servidores de Google.`,
      "Cada visita envía la IP a Google antes de que nadie acepte nada. Una sentencia alemana de 2022 consideró esto una vulneración del RGPD. No es jurisprudencia española, pero el riesgo existe y no compensa.",
      "Descargar las tipografías y servirlas desde el propio dominio. Además carga antes.",
      "p3", "media") : null,
  },
  {
    id: "sin_open_graph", funcion: 7, necesita: ["share.completo"],
    evaluar: (v) => !v.bool("share.completo") ? HP("entiende",
      "El enlace se ve mal al compartirlo",
      "Faltan etiquetas Open Graph: título, descripción o imagen.",
      "Cuando alguien pega la URL en LinkedIn o en WhatsApp sale un cuadro gris sin contexto. En venta B2B, donde el enlace circula por mensaje, eso es una impresión perdida en el peor momento.",
      "Añadir og:title, og:description y og:image. Son tres etiquetas y se ve el efecto al instante.",
      "p2") : null,
  },

  // ======================= 3 · ¿CONFÍA? =======================
  {
    id: "faltan_legales", funcion: 7, necesita: ["confianza.legales_faltan"],
    evaluar: (v) => v.lista("confianza.legales_faltan").length > 0 ? HP("confia",
      "Faltan páginas legales obligatorias",
      `No se encuentran: ${v.lista("confianza.legales_faltan").join(", ")}.`,
      "No es solo confianza: la LSSI obliga a publicar la identificación del prestador, y sin política de privacidad accesible no se pueden recoger datos por formulario de forma válida.",
      "Publicar las páginas que falten y enlazarlas desde el pie y desde el propio formulario.",
      "p1") : null,
  },
  {
    id: "sin_telefono_visible", funcion: 7, necesita: ["confianza.telefono"],
    evaluar: (v) => !v.bool("confianza.telefono") ? HP("confia",
      "No hay teléfono en ninguna parte",
      "No se encuentra ni enlace de llamada ni número en el texto.",
      "En B2B con ticket alto, una parte de los interesados quiere hablar con alguien antes de dejar sus datos. Sin teléfono, esos no se convierten en lead: desaparecen.",
      "Poner el teléfono en la cabecera y en el pie, como enlace pulsable.",
      "p2") : null,
  },
  {
    id: "sin_prueba", funcion: 7, necesita: ["confianza.testimonios", "confianza.cifras"],
    evaluar: (v) => !v.bool("confianza.testimonios") && v.lista("confianza.cifras").length === 0 ? HP("confia",
      "No hay ninguna prueba verificable",
      "La web no muestra testimonios, ni cifras concretas, ni referencias comprobables.",
      "Todo lo que se dice son afirmaciones propias. Con ticket alto y ciclo largo, eso obliga al visitante a fiarse sin motivo, y la mayoría no lo hace.",
      "Añadir dos o tres pruebas concretas: una cifra real, un testimonio con nombre, logos de cliente. Vale más una verificable que diez adjetivos.",
      "p1") : null,
  },
  {
    id: "sin_identificacion_fiscal", funcion: 7, necesita: ["confianza.cif"],
    evaluar: (v) => !v.bool("confianza.cif") ? HP("confia",
      "No se publica la identificación fiscal",
      "No aparece CIF ni razón social en la web.",
      "La LSSI lo exige a cualquier empresa con actividad económica en internet. Además, en B2B es de las primeras cosas que comprueba un comprador prudente.",
      "Incluir denominación social y CIF en el aviso legal y en el pie.",
      "p2") : null,
  },

  // ======================= 4 · ¿PUEDE? =======================
  {
    id: "sin_formulario_captacion", funcion: 7, necesita: ["form.existe"],
    evaluar: (v) => !v.bool("form.existe") ? HP("puede",
      "No hay formulario de captación",
      "La página no tiene ningún formulario de contacto.",
      "Todo el que llega convencido tiene que buscar otra vía. Cada paso extra se lleva una parte, y de los que se van no queda ni rastro.",
      "Poner un formulario corto y medir su envío como conversión. Sin esto, cualquier inversión en captación se mide a ciegas.",
      "p0") : null,
  },
  {
    id: "formulario_largo", funcion: 7, necesita: ["form.campos"],
    evaluar: (v) => v.num("form.campos") > 6 ? HP("puede",
      "El formulario pide demasiado",
      `Tiene ${v.num("form.campos")} campos visibles.`,
      "Cada campo de más reduce los envíos, y casi todo lo que se pregunta antes de hablar se puede preguntar durante la llamada.",
      "Dejar nombre, una vía de contacto y como mucho una pregunta que sirva para cualificar. El resto, en la conversación.",
      "p2") : null,
  },
  {
    id: "campos_sin_etiqueta", funcion: 7, necesita: ["form.sin_etiqueta"],
    evaluar: (v) => v.num("form.sin_etiqueta") > 0 ? HP("puede",
      "Campos del formulario sin etiqueta",
      `${v.num("form.sin_etiqueta")} campos no tienen etiqueta accesible: se apoyan solo en el texto de marcador.`,
      "El marcador desaparece en cuanto se empieza a escribir, así que quien se distrae ya no sabe qué campo está rellenando. Y un lector de pantalla no lo anuncia, lo que además es un incumplimiento de accesibilidad.",
      "Poner una etiqueta visible sobre cada campo. El marcador se queda como ejemplo, no como sustituto.",
      "p2") : null,
  },
  {
    id: "telefono_mal_tipado", funcion: 7, necesita: ["form.telefono_tipado"],
    evaluar: (v) => !v.bool("form.telefono_tipado") ? HP("puede",
      "El campo de teléfono no abre el teclado numérico",
      "El campo de teléfono no declara type=tel.",
      "En móvil sale el teclado de letras y hay que cambiarlo a mano para escribir un número. Es fricción gratuita justo en el último paso.",
      "Cambiar el tipo del campo. Es un atributo.",
      "p3") : null,
  },
  {
    id: "form_sin_consentimiento", funcion: 7, necesita: ["form.existe", "form.consentimiento"],
    evaluar: (v) => v.bool("form.existe") && !v.bool("form.consentimiento") ? HP("puede",
      "El formulario no recoge consentimiento",
      "No hay casilla ni texto de consentimiento en el formulario.",
      "Recoger datos de contacto sin consentimiento informado incumple el RGPD, y además impide demostrar después qué aceptó cada persona si alguien reclama.",
      "Añadir la casilla con enlace a la política de privacidad, y guardar el texto literal junto al lead, no una referencia.",
      "p1") : null,
  },
  {
    id: "a11y_graves", funcion: 7, necesita: ["a11y.graves", "a11y.elementos"],
    evaluar: (v) => v.num("a11y.graves") > 0 ? HP("puede",
      "Hay fallos graves de accesibilidad",
      `axe-core detecta ${v.num("a11y.graves")} reglas incumplidas de gravedad alta o crítica, sobre ${v.num("a11y.elementos")} elementos.`,
      "Hay personas que no pueden usar la web. Además, la directiva europea de accesibilidad y la Ley 11/2023 obligan a determinados servicios digitales: conviene comprobar si el negocio entra en el ámbito, porque entonces deja de ser una recomendación.",
      "Empezar por las reglas críticas, que suelen ser pocas y repetidas. La detección automática cubre la parte mecánica; lo que depende de contexto necesita una revisión aparte.",
      "p1") : null,
  },
  {
    id: "contraste_insuficiente", funcion: 7, necesita: ["a11y.contraste"],
    evaluar: (v) => v.num("a11y.contraste") >= 5 ? HP("puede",
      "Texto con poco contraste",
      `${v.num("a11y.contraste")} elementos no llegan al contraste mínimo.`,
      "Cuesta leerlo con luz de día en el móvil, que es donde se lee. No es un problema de accesibilidad solamente: es de todo el mundo.",
      "Oscurecer los grises de texto hasta alcanzar la relación 4,5:1. Se corrige en la hoja de estilos, sin tocar el diseño.",
      "p2") : null,
  },
  {
    id: "tocables_pequeños", funcion: 7, necesita: ["movil.tocables_pequeños", "movil.tocables_ilegales"],
    evaluar: (v) => v.num("movil.tocables_ilegales") > 0 ? HP("puede",
      "Hay botones demasiado pequeños para el dedo",
      `${v.num("movil.tocables_ilegales")} elementos pulsables están por debajo de los 24 px que exige WCAG 2.2, y ${v.num("movil.tocables_pequeños")} por debajo de los 44 px recomendados.`,
      "Se falla al pulsar y se acaba tocando lo de al lado. En un menú o en un botón de envío, eso es abandono directo.",
      "Ampliar el área pulsable con relleno. No hace falta que el elemento se vea más grande.",
      "p2") : null,
  },
  {
    id: "a11y_ok", funcion: 7, necesita: ["a11y.violaciones", "a11y.graves"],
    evaluar: (v) => v.num("a11y.violaciones") <= 2 && v.num("a11y.graves") === 0 ? HP("puede",
      "La accesibilidad está cuidada",
      `Solo ${v.num("a11y.violaciones")} incidencias automáticas y ninguna grave.`,
      "Poca gente llega aquí. Significa que la web se puede usar con lector de pantalla y con el teclado, y que el contraste está bien resuelto.",
      "Mantenerlo: comprobarlo cada vez que se añada una sección nueva.",
      "p3", "alta", true) : null,
  },
];
