import { type SeoCapability } from "./types";

const commonExclusions = [
  "Sin ejecucion de scripts Python de Claude SEO en esta entrega.",
  "Sin peticiones a proveedores externos ni lectura automatica de credenciales ambientales.",
  "Los resultados futuros seran evidencia o propuesta; no acciones aprobadas.",
];

export const SEO_CAPABILITIES: SeoCapability[] = [
  {
    id: "auditoria_completa",
    name: "Auditoria SEO completa",
    description:
      "Contrato paraguas para revisar alcance, evidencias, cobertura y limitaciones antes de un plan.",
    responsiblePod: "Auditoría SEO",
    claudeSeoComponent: "skills/seo-audit/SKILL.md",
    type: "conocimiento",
    requiredData: [
      "dominio principal",
      "URLs iniciales",
      "servicios contratados",
      "mercados",
      "idiomas",
    ],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Disenada para seleccionar checks futuros dentro del encargo autorizado.",
    requiresHumanApproval: true,
    dependencies: ["onboarding_validado", "alcance_autorizado"],
    expectedOutput: "Hallazgos con evidencia, cobertura por servicio y limitaciones declaradas.",
    integrationState: "disenada",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["SEO", "SEO técnico", "Contenidos", "AEO", "GEO"],
  },
  {
    id: "crawling",
    name: "Crawling",
    description: "Inventario futuro de URLs dentro de dominios y limites autorizados.",
    responsiblePod: "Auditoría SEO",
    claudeSeoComponent: "scripts de fetch/render/discovery y extensiones Firecrawl/Unlighthouse",
    type: "script",
    requiredData: ["dominio", "semillas", "limites de paginas", "paths incluidos/excluidos"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation:
      "Pendiente de adaptador con robots, rate limit, timeouts y aislamiento por tenant.",
    requiresHumanApproval: true,
    dependencies: ["auditoria_completa"],
    expectedOutput: "Inventario de URLs y evidencias de rastreo.",
    integrationState: "referencia",
    risksAndLimitations: [
      ...commonExclusions,
      "Un crawler real puede consumir recursos y debe limitarse por scope.",
    ],
    relatedServiceIds: ["SEO", "SEO técnico"],
  },
  {
    id: "seo_tecnico",
    name: "SEO tecnico",
    description:
      "Revision de rastreabilidad, indexabilidad, canonicals, redirects, rendimiento y marcado.",
    responsiblePod: "SEO técnico",
    claudeSeoComponent: "skills/seo-technical/SKILL.md",
    type: "conocimiento",
    requiredData: ["URLs", "HTML o artefactos", "scope tecnico"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Checks locales sobre artefactos aportados antes de fetch real.",
    requiresHumanApproval: true,
    dependencies: ["crawling"],
    expectedOutput: "Hallazgos tecnicos priorizados con evidencia.",
    integrationState: "disenada",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["SEO técnico"],
  },
  {
    id: "indexacion",
    name: "Indexacion",
    description:
      "Separar senales tecnicas de estado observado en Google cuando exista acceso autorizado.",
    responsiblePod: "Analítica e informes",
    claudeSeoComponent: "gsc_inspect.py y gsc_query.py",
    type: "api",
    requiredData: ["URLs", "propiedad GSC autorizada"],
    requiredAccess: ["Search Console"],
    mode: "lectura",
    possibleAutomation: "Solo con conector GSC de lectura y property autorizada.",
    requiresHumanApproval: true,
    dependencies: ["search_console"],
    expectedOutput: "Estado observado, canonical declarado/elegido y fuente fechada.",
    integrationState: "referencia",
    risksAndLimitations: [
      ...commonExclusions,
      "Robots/noindex/canonical no prueban por si solos el estado en Google.",
    ],
    relatedServiceIds: ["SEO", "SEO técnico"],
  },
  {
    id: "sitemap",
    name: "Sitemap",
    description: "Descubrimiento y validacion futura de sitemaps declarados.",
    responsiblePod: "SEO técnico",
    claudeSeoComponent: "skills/seo-sitemap/SKILL.md y sitemap_discovery.py",
    type: "script",
    requiredData: ["dominio", "robots.txt", "sitemap XML o URLs"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Lectura y propuesta; envio a GSC queda fuera.",
    requiresHumanApproval: true,
    dependencies: ["crawling"],
    expectedOutput: "Estado de sitemap, errores y URLs afectadas.",
    integrationState: "referencia",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["SEO técnico"],
  },
  {
    id: "robots_txt",
    name: "robots.txt",
    description: "Revision de reglas por user-agent y rutas relevantes.",
    responsiblePod: "SEO técnico",
    claudeSeoComponent: "seo-technical, seo-geo y sitemap_discovery.py",
    type: "conocimiento",
    requiredData: ["robots.txt", "paths relevantes", "bots objetivo"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Parseo futuro de robots dentro de scope.",
    requiresHumanApproval: true,
    dependencies: ["crawling"],
    expectedOutput: "Reglas aplicables y riesgos de rastreo.",
    integrationState: "disenada",
    risksAndLimitations: [
      ...commonExclusions,
      "Editar robots.txt es escritura externa y requiere aprobacion separada.",
    ],
    relatedServiceIds: ["SEO técnico", "AEO", "GEO"],
  },
  {
    id: "canonical",
    name: "Canonical",
    description: "Comparacion entre canonical declarado, variantes y evidencia disponible.",
    responsiblePod: "SEO técnico",
    claudeSeoComponent: "parse_html.py, seo-technical y gsc_inspect.py",
    type: "script",
    requiredData: ["HTML", "URLs alternativas"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Check local sobre HTML aportado; GSC queda como fase separada.",
    requiresHumanApproval: true,
    dependencies: ["seo_tecnico"],
    expectedOutput: "Hallazgos sobre canonicals ausentes, conflictivos o incoherentes.",
    integrationState: "referencia",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["SEO técnico"],
  },
  {
    id: "redirects",
    name: "Redirects",
    description: "Registro futuro de codigos, cadenas y destinos dentro del alcance.",
    responsiblePod: "SEO técnico",
    claudeSeoComponent: "fetch/render y seo-technical",
    type: "script",
    requiredData: ["URLs", "limite de redirects", "paths autorizados"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Medicion de lectura; aplicacion de redirects queda excluida.",
    requiresHumanApproval: true,
    dependencies: ["crawling"],
    expectedOutput: "Cadenas, bucles, destinos y prioridad.",
    integrationState: "referencia",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["SEO técnico"],
  },
  {
    id: "core_web_vitals",
    name: "Core Web Vitals",
    description: "Lectura futura de LCP, INP y CLS separando campo y laboratorio.",
    responsiblePod: "Analítica e informes",
    claudeSeoComponent: "pagespeed_check.py, crux_history.py, lcp_subparts.py",
    type: "api",
    requiredData: ["URLs u origen", "dispositivo", "periodo"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Pendiente de adaptador PSI/CrUX con cuotas y fuente explicita.",
    requiresHumanApproval: true,
    dependencies: ["pagespeed", "crux"],
    expectedOutput: "Metricas fechadas con nivel URL/origen y dispositivo.",
    integrationState: "referencia",
    risksAndLimitations: [...commonExclusions, "No mezclar datos de laboratorio con campo real."],
    relatedServiceIds: ["SEO técnico"],
  },
  {
    id: "pagespeed",
    name: "PageSpeed",
    description: "Consulta futura de Lighthouse/PSI con estrategia y fecha.",
    responsiblePod: "SEO técnico",
    claudeSeoComponent: "pagespeed_check.py",
    type: "api",
    requiredData: ["URL", "estrategia mobile/desktop"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Disenada; requiere red externa y cuotas, no activadas.",
    requiresHumanApproval: true,
    dependencies: ["seo_tecnico"],
    expectedOutput: "Auditoria de laboratorio con fuente PageSpeed.",
    integrationState: "referencia",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["SEO técnico"],
  },
  {
    id: "crux",
    name: "CrUX",
    description: "Consulta futura de datos de campo CrUX por URL u origen.",
    responsiblePod: "Analítica e informes",
    claudeSeoComponent: "crux_history.py",
    type: "api",
    requiredData: ["URL u origen", "periodo", "dispositivo"],
    requiredAccess: [],
    mode: "lectura",
    possibleAutomation: "Disenada para lectura con fuente y periodo.",
    requiresHumanApproval: true,
    dependencies: ["core_web_vitals"],
    expectedOutput: "P75 y distribuciones cuando exista muestra.",
    integrationState: "referencia",
    risksAndLimitations: [
      ...commonExclusions,
      "La falta de muestra no debe inventarse ni rellenarse.",
    ],
    relatedServiceIds: ["SEO técnico"],
  },
  {
    id: "search_console",
    name: "Search Console",
    description:
      "Lectura futura de Search Analytics, sitemaps e inspeccion URL con permiso explicito.",
    responsiblePod: "Analítica e informes",
    claudeSeoComponent: "gsc_query.py y gsc_inspect.py",
    type: "api",
    requiredData: ["property", "fechas", "dimensiones", "URLs"],
    requiredAccess: ["Search Console"],
    mode: "lectura",
    possibleAutomation: "Solo con conector seguro y acceso de lectura autorizado.",
    requiresHumanApproval: true,
    dependencies: ["onboarding_accesos"],
    expectedOutput: "Metricas GSC con filtros, fecha y propiedad.",
    integrationState: "referencia",
    risksAndLimitations: [
      ...commonExclusions,
      "No heredar credenciales ambientales ni asumir acceso por conocer una property.",
    ],
    relatedServiceIds: ["SEO", "SEO técnico"],
  },
  {
    id: "ga4",
    name: "GA4",
    description: "Lectura futura de sesiones, landing pages y conversiones organicas.",
    responsiblePod: "Analítica e informes",
    claudeSeoComponent: "ga4_report.py",
    type: "api",
    requiredData: ["property GA4", "fechas", "eventos/conversiones"],
    requiredAccess: ["GA4"],
    mode: "lectura",
    possibleAutomation: "Solo con acceso validado y definicion de conversiones.",
    requiresHumanApproval: true,
    dependencies: ["onboarding_accesos"],
    expectedOutput: "Metricas GA4 separadas de GSC y con limitaciones.",
    integrationState: "referencia",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["SEO", "Analítica"],
  },
  {
    id: "schema_org",
    name: "schema.org",
    description: "Revision y propuestas de marcado estructurado verificable.",
    responsiblePod: "SEO técnico",
    claudeSeoComponent: "skills/seo-schema/SKILL.md y schema_generate.py",
    type: "script",
    requiredData: ["HTML", "hechos verificables del negocio", "tipo de pagina"],
    requiredAccess: [],
    mode: "generacion_propuesta",
    possibleAutomation: "Generacion de propuesta; insertar marcado requiere aprobacion separada.",
    requiresHumanApproval: true,
    dependencies: ["seo_tecnico"],
    expectedOutput: "JSON-LD propuesto y advertencias.",
    integrationState: "disenada",
    risksAndLimitations: [...commonExclusions, "No inventar ratings, precios, autorias ni hechos."],
    relatedServiceIds: ["SEO técnico", "AEO", "GEO"],
  },
  {
    id: "contenido",
    name: "Contenido",
    description: "Revision editorial, claims, fuentes y oportunidades de mejora.",
    responsiblePod: "Contenidos",
    claudeSeoComponent: "skills/seo-content/SKILL.md",
    type: "conocimiento",
    requiredData: ["texto o HTML", "intencion", "fuentes permitidas", "idioma"],
    requiredAccess: [],
    mode: "generacion_propuesta",
    possibleAutomation: "Borradores o recomendaciones; publicacion queda excluida.",
    requiresHumanApproval: true,
    dependencies: ["auditoria_completa"],
    expectedOutput: "Hallazgos editoriales y propuestas revisables.",
    integrationState: "disenada",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["Contenidos", "SEO"],
  },
  {
    id: "eeat",
    name: "E-E-A-T",
    description: "Criterios de experiencia, autoridad, confianza y evidencia editorial.",
    responsiblePod: "Contenidos",
    claudeSeoComponent: "references/eeat-framework.md y seo-content",
    type: "conocimiento",
    requiredData: ["autoria", "fuentes", "claims", "politicas editoriales"],
    requiredAccess: [],
    mode: "generacion_propuesta",
    possibleAutomation: "Checklist y gaps; no es metrica oficial.",
    requiresHumanApproval: true,
    dependencies: ["contenido"],
    expectedOutput: "Riesgos E-E-A-T y acciones propuestas.",
    integrationState: "referencia",
    risksAndLimitations: [...commonExclusions, "No presentar como score oficial de Google."],
    relatedServiceIds: ["Contenidos", "AEO", "GEO"],
  },
  {
    id: "keyword_research",
    name: "Keyword research",
    description: "Investigacion futura con mercado, idioma, fuente y fecha explicitos.",
    responsiblePod: "Estrategia y planificación",
    claudeSeoComponent: "keyword_planner.py, seo-dataforseo, seo-content-brief",
    type: "api",
    requiredData: ["semillas", "mercado", "idioma", "competidores autorizados"],
    requiredAccess: ["Proveedor de keywords"],
    mode: "lectura",
    possibleAutomation: "Pendiente de proveedor autorizado y coste aprobado.",
    requiresHumanApproval: true,
    dependencies: ["auditoria_completa"],
    expectedOutput: "Ideas, volumen/dificultad si existe fuente y limitaciones.",
    integrationState: "referencia",
    risksAndLimitations: [
      ...commonExclusions,
      "No fabricar volumen a partir de busquedas web o intuicion.",
    ],
    relatedServiceIds: ["SEO", "Contenidos"],
  },
  {
    id: "semantic_clustering",
    name: "Semantic clustering",
    description: "Agrupacion por intencion/SERP y propuesta de arquitectura.",
    responsiblePod: "Estrategia y planificación",
    claudeSeoComponent: "skills/seo-cluster/SKILL.md",
    type: "conocimiento",
    requiredData: ["keywords", "mercado", "idioma", "SERP o criterio declarado"],
    requiredAccess: [],
    mode: "generacion_propuesta",
    possibleAutomation: "Propuesta de clusters; ejecucion editorial queda desacoplada.",
    requiresHumanApproval: true,
    dependencies: ["keyword_research"],
    expectedOutput: "Mapa de clusters y relacion con contenidos.",
    integrationState: "disenada",
    risksAndLimitations: commonExclusions,
    relatedServiceIds: ["SEO", "Contenidos"],
  },
  {
    id: "aeo_geo_citabilidad",
    name: "AEO/GEO y citabilidad",
    description:
      "Revision de pasajes citables, fuentes y presencia preparada para respuestas generativas.",
    responsiblePod: "AEO/GEO y citabilidad",
    claudeSeoComponent: "skills/seo-geo/SKILL.md y content_verify.py",
    type: "conocimiento",
    requiredData: ["claims", "fuentes", "entidades", "mercado", "idioma"],
    requiredAccess: [],
    mode: "generacion_propuesta",
    possibleAutomation:
      "Analisis y propuestas; medicion externa de menciones queda para conectores futuros.",
    requiresHumanApproval: true,
    dependencies: ["contenido", "schema_org"],
    expectedOutput: "Claims citables, fuentes faltantes y limitaciones.",
    integrationState: "disenada",
    risksAndLimitations: [
      ...commonExclusions,
      "Estar preparado para ser citado no prueba visibilidad en un LLM.",
    ],
    relatedServiceIds: ["AEO", "GEO", "Contenidos"],
  },
];

export function listSeoCapabilities() {
  return SEO_CAPABILITIES.map((capability) => ({ ...capability }));
}

export function getSeoCapability(id: string): SeoCapability | undefined {
  return SEO_CAPABILITIES.find((capability) => capability.id === id);
}
